# Generated by Django 2.2.7 on 2019-11-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='publication_date',
            field=models.DateTimeField(verbose_name='Datefield'),
        ),
    ]
